<a href="https://colab.research.google.com/github/Caglarcakmak0/Makineogrenmesi/blob/main/Cross_Validation_Score_Analysis_w_Iris_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
 from sklearn.linear_model import LogisticRegression
 from sklearn.svm import SVC
 from sklearn.ensemble import RandomForestClassifier
 import numpy as np
 import pandas as pd
from  sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

In [34]:
df_iris= load_iris()


In [35]:
from sklearn.model_selection import cross_val_score

In [36]:
## for linear regression
lr_scores= cross_val_score(LogisticRegression(), df_iris.data, df_iris.target)
lr_scores


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [37]:
np.average(lr_scores)

0.9733333333333334

In [38]:
rf_scores= cross_val_score(RandomForestClassifier(), df_iris.data, df_iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [39]:
np.average(rf_scores)

0.96

In [40]:
d_scores= cross_val_score(DecisionTreeClassifier(), df_iris.data, df_iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [41]:
np.average(d_scores)

0.9533333333333334